name: mobile

on:
  push:
    paths:
      - "mobile/**"
      - ".github/workflows/mobile.yml"
  pull_request:
    paths:
      - "mobile/**"

defaults:
  run:
    working-directory: mobile

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Generate platform folders
        run: flutter create . --platforms=android,ios --project-name sc_platform_mobile
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Test
        run: flutter test
